### PR TITLE
RBAC client support

### PR DESCRIPTION
**Pull request by 5abeel**
This PR introduces role-based access control of p4 client as specified in the P4 Spec

### CODE REVIEW

**Comment by vinintel** [comment]
Can you confirm what are the test cases executed on this change ?

**Comment by 5abeel** [comment]
Changing this PR to draft mode.

I couldnt complete an end-to-end test with running IPsec recipe on my test setup.

I pulled out the code specific to the p4rt_client and ran it as an independent program to test it. Adding the role name seems to fail from ipsec_p4_client and rejected based on the MasterArbitrationUpdate message contents by the infrap4d/stratum server.

Since this p4client is written by IPsec team, need insight in understanding what is done differently on initial p4 session establishment by this client. All other p4 clients that I have tested against work fine (`p4runtime-shell`, `p4_pipeline_pusher`, `ovs-p4rt`, `p4rt-ctl` -- all these p4 clients are able to push messages and set role names).

**Comment by 5abeel** [comment]
Re-tested the code pulled out into a separate application after a bug fix on the server side. 

I can set the pipeline now with the role names included. Updating this PR from draft to open for review.

**Comment by 5abeel** [comment]
End-to-end validation has been completed.

After starting IPsec-Recipe, confirmed:
* Initial IKE handshake is successsful
* P4 message gets through successfully with role config name (see `ipsec-ss-plugin` in logs)
* Confirmed that pipe is set by getting the pipe data from p4rt-ctl
* Saw counters on IMC increment when trying SSH from Host B to Host A


```
[root@fedora sbin]# ./ipsec start
Starting strongSwan 5.9.3 IPsec [starter]...
[root@fedora sbin]# ./ipsec statusall
Status of IKE charon daemon (strongSwan 5.9.3, Linux 5.10.45-p406.gae450b9, x86_64):
  uptime: 22 seconds, since Mar 22 10:44:34 2024
  malloc: sbrk 4591616, mmap 540672, used 1495936, free 3095680
  worker threads: 11 of 16 idle, 5/0/0/0 working, job queue: 0/0/0/0, scheduled: 3
  loaded plugins: charon aes des rc2 sha2 sha1 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp curve25519 xcbc cmac hmac drbg attr ipsec_offload kernel-netlink resolve socket-default stroke vici updown xauth-generic counters
Listening IP addresses:
  10.166.224.130
  172.17.0.1
  192.0.0.1
Connections:
    sts-base:  %any...192.0.0.2  IKEv2
    sts-base:   local:  [192.0.0.1] uses pre-shared key authentication
    sts-base:   remote: [192.0.0.2] uses pre-shared key authentication
    sts-base:   child:  192.0.0.1/32[tcp] === 192.0.0.2/32[tcp] TRANSPORT
Security Associations (1 up, 0 connecting):
    sts-base[1]: ESTABLISHED 21 seconds ago, 192.0.0.1[192.0.0.1]...192.0.0.2[192.0.0.2]
    sts-base[1]: IKEv2 SPIs: bd911d95a8d40b47_i* 44859fbb6d0ef427_r, pre-shared key reauthentication in 2 hours
    sts-base[1]: IKE proposal: AES_CBC_256/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
    sts-base{1}:  INSTALLED, TRANSPORT, reqid 1, ESP SPIs: 45000001_i cb740d33_o
    sts-base{1}:  AES_GCM_16_256, 140034583861488 bytes_i (140034187469280 pkts, 18446604039125940499s ago), 3546922463657997878 bytes_o (4123384315473638706 pkts, 17086213361610734643s ago), rekeying in 42 minutes
    sts-base{1}:   192.0.0.1/32[tcp] === 192.0.0.2/32[tcp]
[root@fedora sbin]#
[root@fedora sbin]#
[root@fedora sbin]# vi /var/log/stratum/infrap4d.INFO
[root@fedora sbin]#
[root@fedora sbin]#
[root@fedora sbin]# grep ipsec_ss_plugin /var/log/stratum/infrap4d.INFO
[root@fedora sbin]# vi /var/log/stratum/infrap4d.INFO
[root@fedora sbin]# grep ipsec-ss-plugin /var/log/stratum/infrap4d.INFO
I20240322 10:44:35.005908 150839 sdn_controller_manager.cc:409] New SDN connection (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38212): device_id: 1 role { name: "ipsec-ss-plugin" } election_id { high: 1 }
I20240322 10:44:35.007054 150839 sdn_controller_manager.cc:462] New primary connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.007083 150839 p4_service.cc:631] Controller (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38212) is connected as MASTER for node (aka device) with ID 1.
I20240322 10:44:35.014228 150839 sdn_controller_manager.cc:506] Dropping primary SDN connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.014919 150951 sdn_controller_manager.cc:409] New SDN connection (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38212): device_id: 1 role { name: "ipsec-ss-plugin" } election_id { high: 1 }
I20240322 10:44:35.015116 150951 sdn_controller_manager.cc:462] New primary connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.015146 150951 p4_service.cc:631] Controller (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38212) is connected as MASTER for node (aka device) with ID 1.
I20240322 10:44:35.059410 150951 sdn_controller_manager.cc:506] Dropping primary SDN connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.200573 150953 sdn_controller_manager.cc:409] New SDN connection (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38220): device_id: 1 role { name: "ipsec-ss-plugin" } election_id { high: 1 }
I20240322 10:44:35.200661 150953 sdn_controller_manager.cc:462] New primary connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.200672 150953 p4_service.cc:631] Controller (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38220) is connected as MASTER for node (aka device) with ID 1.
I20240322 10:44:35.205550 150953 sdn_controller_manager.cc:506] Dropping primary SDN connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
I20240322 10:44:35.232414 150989 sdn_controller_manager.cc:409] New SDN connection (role_name: 'ipsec-ss-plugin', election_id: { high: 1 }, uri: ipv6:%5B::1%5D:38222): device_id: 1 role { name: "ipsec-ss-plugin" } election_id { high: 1 }
I20240322 10:44:35.232476 150989 sdn_controller_manager.cc:462] New primary connection for role 'ipsec-ss-plugin' with election ID { high: 1 }.
[root@fedora sbin]#
[root@fedora sbin]#
[root@fedora sbin]#
[root@fedora sbin]# p4rt-ctl get-pipe br0
Unable to import the 'idpf' modules. The meter commands will not work.
To fix the problem, install an updated version of the python p4runtime package.
P4Info of bridge br0:
pkg_info {
  arch: "pna"
}
tables {
  preamble {
    id: 48773578
    name: "MainControlDecrypt.lem_exception"
    alias: "lem_exception"
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 38116127
    name: "MainControlDecrypt.lem_clear"
    alias: "lem_clear"
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 45068641
    name: "MainControlDecrypt.ipsec_rx_sa_classification_table"
    alias: "ipsec_rx_sa_classification_table"
  }
  match_fields {
    id: 1
    name: "hdrs.ipv4[meta.common.depth].src_ip"
    bitwidth: 32
    match_type: EXACT
  }
  match_fields {
    id: 2
    name: "hdrs.ipv4[meta.common.depth].dst_ip"
    bitwidth: 32
    match_type: EXACT
  }
  match_fields {
    id: 3
    name: "hdrs.esp.spi"
    bitwidth: 32
    match_type: EXACT
  }
  action_refs {
    id: 33177492
  }
  action_refs {
    id: 30285547
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 41233864
    name: "crypto_tunnel_control.ipsec_rx_post_decrypt_table"
    alias: "ipsec_rx_post_decrypt_table"
  }
  match_fields {
    id: 1
    name: "meta.common.crypto_status"
    bitwidth: 1
    match_type: TERNARY
  }
  match_fields {
    id: 2
    name: "meta.common.crypto_offload"
    bitwidth: 1
    match_type: TERNARY
  }
  match_fields {
    id: 3
    name: "meta.common.crypto_tag"
    bitwidth: 16
    match_type: TERNARY
  }
  match_fields {
    id: 4
    name: "hdrs.ipv4[meta.common.depth].dst_ip"
    bitwidth: 32
    match_type: TERNARY
  }
  action_refs {
    id: 16818337
  }
  action_refs {
    id: 26398763
  }
  action_refs {
    id: 31058214
  }
  size: 65536
}
tables {
  preamble {
    id: 36144080
    name: "crypto_tunnel_control.outer_ipv4_decap_mod_table"
    alias: "outer_ipv4_decap_mod_table"
  }
  match_fields {
    id: 1
    name: "meta.common.mod_blob_ptr"
    bitwidth: 24
    match_type: EXACT
  }
  action_refs {
    id: 19827329
  }
  action_refs {
    id: 21257015
  }
  const_default_action_id: 21257015
  size: 1024
}
tables {
  preamble {
    id: 44556728
    name: "crypto_tunnel_control.ipsec_tx_spd_table"
    alias: "ipsec_tx_spd_table"
  }
  match_fields {
    id: 1
    name: "hdrs.ipv4[meta.common.depth].dst_ip"
    bitwidth: 32
    match_type: TERNARY
  }
  action_refs {
    id: 21435079
  }
  action_refs {
    id: 31338975
  }
  action_refs {
    id: 31058214
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 65536
}
tables {
  preamble {
    id: 46182446
    name: "crypto_tunnel_control.ipsec_tx_sa_classification_table"
    alias: "ipsec_tx_sa_classification_table"
  }
  match_fields {
    id: 1
    name: "meta.common.crypto_offload"
    bitwidth: 1
    match_type: EXACT
  }
  match_fields {
    id: 2
    name: "hdrs.ipv4[meta.common.depth].src_ip"
    bitwidth: 32
    match_type: EXACT
  }
  match_fields {
    id: 3
    name: "hdrs.ipv4[meta.common.depth].dst_ip"
    bitwidth: 32
    match_type: EXACT
  }
  match_fields {
    id: 4
    name: "hdrs.ipv4[meta.common.depth].protocol"
    bitwidth: 8
    match_type: EXACT
  }
  action_refs {
    id: 28450616
  }
  action_refs {
    id: 17156783
  }
  action_refs {
    id: 16843195
  }
  action_refs {
    id: 31058214
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 65536
}
tables {
  preamble {
    id: 41572460
    name: "crypto_tunnel_control.outer_ipv4_encap_mod_table"
    alias: "outer_ipv4_encap_mod_table"
  }
  match_fields {
    id: 1
    name: "meta.common.mod_blob_ptr"
    bitwidth: 24
    match_type: EXACT
  }
  action_refs {
    id: 26814003
  }
  action_refs {
    id: 21257015
  }
  const_default_action_id: 21257015
  size: 1024
}
tables {
  preamble {
    id: 37116684
    name: "crypto_tunnel_control.comms_channel_table"
    alias: "comms_channel_table"
  }
  match_fields {
    id: 1
    name: "meta.common.vsi"
    bitwidth: 11
    match_type: EXACT
  }
  match_fields {
    id: 2
    name: "umeta.cmeta.flex16"
    bitwidth: 16
    match_type: EXACT
  }
  action_refs {
    id: 30611252
  }
  action_refs {
    id: 31058214
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 41075306
    name: "crypto_tunnel_control.hash_ipv4_tcp"
    alias: "hash_ipv4_tcp"
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 36380251
    name: "crypto_tunnel_control.hash_ipv4_udp"
    alias: "hash_ipv4_udp"
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
tables {
  preamble {
    id: 37588992
    name: "crypto_tunnel_control.hash_ipv4"
    alias: "hash_ipv4"
  }
  action_refs {
    id: 21257015
    scope: DEFAULT_ONLY
    annotations: "@defaultonly"
  }
  size: 1024
}
actions {
  preamble {
    id: 21257015
    name: "NoAction"
    alias: "NoAction"
    annotations: "@noWarn(\"unused\")"
  }
}
actions {
  preamble {
    id: 30285547
    name: "MainControlDecrypt.ipsec_bypass"
    alias: "MainControlDecrypt.ipsec_bypass"
  }
}
actions {
  preamble {
    id: 33177492
    name: "MainControlDecrypt.ipsec_decrypt"
    alias: "ipsec_decrypt"
  }
  params {
    id: 1
    name: "saidx"
    bitwidth: 24
  }
}
actions {
  preamble {
    id: 32375392
    name: "crypto_tunnel_control.no_modify"
    alias: "no_modify"
  }
}
actions {
  preamble {
    id: 31058214
    name: "crypto_tunnel_control.drop"
    alias: "drop"
  }
}
actions {
  preamble {
    id: 26398763
    name: "crypto_tunnel_control.ipsec_transport_post_decrypt"
    alias: "ipsec_transport_post_decrypt"
  }
}
actions {
  preamble {
    id: 16818337
    name: "crypto_tunnel_control.ipsec_tunnel_post_decrypt"
    alias: "ipsec_tunnel_post_decrypt"
  }
  params {
    id: 1
    name: "inner_nexthop_id"
    bitwidth: 24
  }
}
actions {
  preamble {
    id: 19827329
    name: "crypto_tunnel_control.decap_outer_ipv4_mod"
    alias: "decap_outer_ipv4_mod"
  }
  params {
    id: 1
    name: "inner_dmac"
    bitwidth: 48
  }
  params {
    id: 2
    name: "inner_smac"
    bitwidth: 48
  }
}
actions {
  preamble {
    id: 31338975
    name: "crypto_tunnel_control.ipsec_bypass"
    alias: "crypto_tunnel_control.ipsec_bypass"
  }
}
actions {
  preamble {
    id: 21435079
    name: "crypto_tunnel_control.ipsec_protect"
    alias: "ipsec_protect"
  }
}
actions {
  preamble {
    id: 28450616
    name: "crypto_tunnel_control.ipsec_tx_tunnel"
    alias: "ipsec_tx_tunnel"
  }
  params {
    id: 1
    name: "saidx"
    bitwidth: 24
  }
  params {
    id: 2
    name: "tunnel_id"
    bitwidth: 24
  }
}
actions {
  preamble {
    id: 17156783
    name: "crypto_tunnel_control.ipsec_tx_transport"
    alias: "ipsec_tx_transport"
  }
  params {
    id: 1
    name: "saidx"
    bitwidth: 24
  }
}
actions {
  preamble {
    id: 16843195
    name: "crypto_tunnel_control.ipsec_tx_transport_udp"
    alias: "ipsec_tx_transport_udp"
  }
  params {
    id: 1
    name: "saidx"
    bitwidth: 24
  }
}
actions {
  preamble {
    id: 30611252
    name: "crypto_tunnel_control.send"
    alias: "send"
  }
  params {
    id: 1
    name: "port"
    bitwidth: 32
    type_name {
      name: "PortId_t"
    }
  }
}
actions {
  preamble {
    id: 32396431
    name: "crypto_tunnel_control.outer_tcp_transport_encap"
    alias: "outer_tcp_transport_encap"
  }
}
actions {
  preamble {
    id: 22190132
    name: "crypto_tunnel_control.outer_udp_transport_encap"
    alias: "outer_udp_transport_encap"
  }
}
actions {
  preamble {
    id: 26814003
    name: "crypto_tunnel_control.encap_outer_ipv4_mod"
    alias: "encap_outer_ipv4_mod"
  }
  params {
    id: 1
    name: "src_addr"
    bitwidth: 32
  }
  params {
    id: 2
    name: "dst_addr"
    bitwidth: 32
  }
  params {
    id: 3
    name: "proto"
    bitwidth: 8
  }
  params {
    id: 4
    name: "smac"
    bitwidth: 48
  }
  params {
    id: 5
    name: "dmac"
    bitwidth: 48
  }
}
type_info {
  new_types {
    key: "PortId_t"
    value {
      translated_type {
        uri: "p4.org/pna/v1/PortId_t"
        sdn_bitwidth: 32
      }
    }
  }
}

```

**Comment by 5abeel** [comment]
> @5abeel can you also add p4rt-ctl dump entries output and IMC counter output

dump-entries output:

```
[root@fedora sbin]# p4rt-ctl dump-entries br0
Unable to import the 'idpf' modules. The meter commands will not work.
To fix the problem, install an updated version of the python p4runtime package.
Table entries for bridge br0:
  table=MainControlDecrypt.ipsec_rx_sa_classification_table hdrs.ipv4[meta.common.depth].src_ip=0xc0000002,hdrs.ipv4[meta.common.depth].dst_ip=0xc0000001,hdrs.esp.spi=0x48000001 actions=MainControlDecrypt.ipsec_decrypt(saidx=0x000001)
  table=crypto_tunnel_control.ipsec_tx_spd_table priority=1 hdrs.ipv4[meta.common.depth].dst_ip=0xc0000002/b'\xff\xff\xff\xff' actions=crypto_tunnel_control.ipsec_protect()
  table=crypto_tunnel_control.ipsec_tx_sa_classification_table meta.common.crypto_offload=0x00,hdrs.ipv4[meta.common.depth].src_ip=0xc0000001,hdrs.ipv4[meta.common.depth].dst_ip=0xc0000002,hdrs.ipv4[meta.common.depth].protocol=0x06 actions=NoAction()
[root@fedora sbin]#
```

counters from IMC:

```
[root@ipu-imc scripts]# cli_client -qsS
No IP address specified, defaulting to localhost
ipsec rx dec packets: 5 bytes: 200
ipsec rx replay errors: 0
ipsec rx auth failures: 13
ipsec rx misc errors: 0
ipsec rx bad pkts: 0
ipsec tx enc packets: 3 bytes: 120
ipsec tx misc errors: 0
ipsec tx bad pkts: 0
cisp rx dec packets: 0 bytes: 0
cisp rx auth failures: 0
cisp rx misc errors: 0
cisp rx bad pkts: 0
cisp tx enc packets: 0 bytes: 0
cisp tx misc errors: 0
cisp tx bad pkts: 0

server finished responding =======================
[root@ipu-imc scripts]#
```

**Comment by vinintel** [comment]
LGTM

**Pull request merged**
